---
# Make a quick pki that will boot strap something useable
- include: pki.yml
  when: pki_dir is defined

- include: packages.yml

- include: demopki.yml
  when: pki_dir is not defined

- include: ovpn.yml

- include: ovpn-gateway.yml
  loop: "{{ openvpn_instances }}"
  loop_control:
    loop_var: vpn_instance
  when: create_gateways

- include: ovpn-security.yml

- include: ovpn-iptables.yml
  loop: "{{ openvpn_instances }}"
  loop_control:
    loop_var: vpn_instance
