
# Make a quick pki that will boot strap something useable
- debug: 
    msg: "pki_dir is required"
  failed_when: pki_dir is not defined

- include: packages.yml

- include: ovpn.yml

- include: ovpn-gateways.yml

- include: ovpn-security.yml