---
- name: OpenVPN | sysctl | Enable IPv4 traffic forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'

- name: OpenVPN | Directories | Create Extra files
  copy:
    content: ""
    dest: "/etc/openvpn/server/openvpn-{{ item.proto }}-{{ item.port }}.log"
    force: false
    group: openvpn
    owner: openvpn
    mode: '0660'
  with_items: "{{ openvpn_instances }}"

- name: OpenVPN | SELinux | Allow write to log file
  shell: "semanage fcontext -a -t openvpn_var_log_t /etc/openvpn/server/openvpn-{{ item.proto }}-{{ item.port }}.log"
  changed_when: false
  become: true
  with_items: "{{ openvpn_instances }}"
  tags:
    - skip_ansible_lint
  when: (ansible_virtualization_type != "docker")

- name: OpenVPN | SELinux | Make fixes effective
  shell: "restorecon /etc/openvpn/server/openvpn-{{ item.proto }}-{{ item.port }}.log"
  changed_when: false
  become: true
  with_items: "{{ openvpn_instances }}"
  tags:
    - skip_ansible_lint
  when: (ansible_virtualization_type != "docker")

- name: OpenVPN | Directories | Create CCD
  file:
    path: /etc/openvpn/server/ccd-{{ item.proto }}-{{ item.port }}
    state: directory
    owner: openvpn
    group: openvpn
    mode: 0750
  with_items: "{{ openvpn_instances }}"

- name: OpenVPN | Configuration | Copy OpenVPN server configuration files into place
  template:
    src: etc_openvpn_server.conf.j2
    dest: "{{ openvpn_remotedir }}/{{ item.proto }}-{{ item.port }}.conf"
    owner: openvpn
    group: openvpn
    mode: 0440
  with_items: "{{ openvpn_instances }}"
  notify:
    - restart_openvpn

- name: OpenVPN | LogRotate | Set the logrotate configuration
  template:
    src: etc_logrotate_logrotated_openvpn.j2
    dest: "/etc/logrotate.d/openvpn.logrotate"
    mode: 0440
