- name: OpenVPN | PKI | Deploy server Cert
  copy:
    src: '{{ pki_dir }}/vpn.pem'
    dest: '{{ openvpn_remoteserver_cert }}'
    group: openvpn
    owner: openvpn
    mode: 0440
  become: true
  notify:
    restart_openvpn

- name: OpenVPN | PKI | Deploy server key
  copy:
    src: '{{ pki_dir }}/vpn.key'
    dest: '{{ openvpn_remoteserver_key }}'
    group: openvpn
    owner: openvpn
    mode: 0400
  become: true
  notify:
    restart_openvpn

- name: OpenVPN | PKI | Deploy ta.key
  copy:
    src: '{{ pki_dir }}/ta.key'
    dest: '{{ openvpn_remotehmac_firewall }}'
    group: openvpn
    owner: openvpn
    mode: 0400
  become: true
  notify:
    restart_openvpn

- name: OpenVPN | PKI | Deploy CRL
  copy:
    src: '{{ pki_dir }}/crl.pem'
    dest: '{{ openvpn_remotecrl }}'
    group: openvpn
    owner: openvpn
    mode: 0440
  become: true
  notify:
    restart_openvpn

- name: OpenVPN | PKI | Deploy CA
  copy:
    src: '{{ pki_dir }}/ca.pem'
    dest: '{{ openvpn_remoteca }}'
    group: openvpn
    owner: openvpn
    mode: 0440
  become: true
  notify:
    restart_openvpn

- name: OpenVPN | PKI | Deploy DH
  copy:
    src: '{{ pki_dir }}/dh.pem'
    dest: '{{ openvpn_remotedh }}'
    group: openvpn
    owner: openvpn
    mode: 0440
  become: true
  notify:
    restart_openvpn