- name: Openvpn | Handlers | Restart vpns
  service:
    name: "openvpn@{{ item.proto }}-{{ item.port }}.service"
    state: restarted
  with_items: "{{ openvpn_instances }}"  
  listen: restart_openvpn